name: x25519
description: An implementation of the X25519 key exchange algorithm for secure, efficient elliptic curve cryptography as per RFC 7748.
version: 1.0.0
repository: https://github.com/carlosmakin/x25519

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
